[package]
name = "l337-postgres"
version = "0.1.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>"]

[dependencies]
l337 = { path = ".." }
futures = "0.1.14"
tokio = "0.1.8"
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres.git" }
