[package]
name = "l337-postgres-futures3"
version = "0.1.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]

[dependencies]
l337-futures3 = { path = ".." }
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
tokio = "0.1.8"
tokio-postgres = "0.4.0-rc.2"
